name: Docker Registry Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: whoan/docker-build-with-cache-action@v2
        with:
          context: "${{ secrets.WEBSERVER_CONTAINER_DIRECTORY }}"
          image_name: "${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ secrets.WEBSERVER_IMAGE_NAME }}"
          registry: "${{ secrets.DOCKER_REGISTRY_URL }}"
          username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
